# Generated by Django 6.0.6 on 2026-06-25 16:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=300)),
                ('venue_details', models.TextField(blank=True)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('couple_photo', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.event')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Lista de Tareas',
                'ordering': ['priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VENUE', 'Lugar'), ('CATERING', 'Catering'), ('ATTIRE', 'Vestuario'), ('PHOTOGRAPHY', 'Fotografía'), ('FLOWERS', 'Flores'), ('MUSIC', 'Música'), ('TRANSPORT', 'Transporte'), ('OTHER', 'Otros')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='core.event')),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Presupuesto',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PLANNER', 'Wedding Planner'), ('GUEST', 'Invitado')], default='GUEST', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.event')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('PREPARATIVES', 'Preparativos'), ('CEREMONY', 'Ceremonia'), ('RECEPTION', 'Recepción'), ('OTHER', 'Otros')], default='OTHER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.event')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=8)),
                ('shape', models.CharField(choices=[('CIRCULAR', 'Circular'), ('RECTANGULAR', 'Rectangular')], default='CIRCULAR', max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('is_head_table', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.event')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(choices=[('NOVIA', 'Familia de la Novia'), ('NOVIO', 'Familia del Novio'), ('AMIGOS_NOVIA', 'Amigos de la Novia'), ('AMIGOS_NOVIO', 'Amigos del Novio'), ('TRABAJO', 'Compañeros de Trabajo'), ('OTROS', 'Otros')], max_length=20)),
                ('rsvp_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('DECLINED', 'Rechazado')], default='PENDING', max_length=20)),
                ('meal_choice', models.CharField(choices=[('STANDARD', 'Menú Estándar'), ('VEGETARIAN', 'Vegetariano'), ('VEGAN', 'Vegano'), ('CELIAC', 'Sin Gluten')], default='STANDARD', max_length=20)),
                ('plus_one', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.event')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='core.table')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['full_name'],
            },
        ),
    ]
