# Generated by Django 6.0.6 on 2026-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bride_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de la Novia'),
        ),
        migrations.AddField(
            model_name='event',
            name='groom_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Novio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
