# Generated by Django 6.0.6 on 2026-06-30 15:49

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    Guest = apps.get_model('core', 'Guest')
    for guest in Guest.objects.all():
        guest.invitation_token = uuid.uuid4()
        guest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guest_linked_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_tokens),
        migrations.AlterField(
            model_name='guest',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
