# Generated by Django 6.0.6 on 2026-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guest_invitation_sent_guest_invitation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='design_template',
            field=models.CharField(choices=[('classic_romance', 'Romance Clásico'), ('modern_minimal', 'Minimalista Moderno'), ('rustic_boho', 'Rústico Boho'), ('art_deco', 'Art Deco'), ('floral_romantic', 'Floral Romántico')], default='classic_romance', max_length=20, verbose_name='Diseño de Invitación'),
        ),
    ]
