# Generated by Django 6.0.6 on 2026-06-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_design_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_button_text',
            field=models.CharField(default='Confirmar Asistencia', max_length=50, verbose_name='Texto del botón'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_closing',
            field=models.CharField(default='Con amor', max_length=100, verbose_name='Cierre del correo'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_header',
            field=models.CharField(default='Estás invitado', max_length=100, verbose_name='Encabezado del correo'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_message',
            field=models.TextField(default='Nos llena de alegría compartir este momento tan especial contigo', verbose_name='Mensaje principal del correo'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_question',
            field=models.CharField(default='¿nos acompañarás?', max_length=100, verbose_name='Pregunta de confirmación'),
        ),
    ]
